# Generated by Django 3.2.9 on 2021-12-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=200)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSSV', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=150)),
                ('CurrentAddress', models.CharField(max_length=150)),
                ('JobAddressWorld', models.CharField(max_length=150)),
                ('JobAddress', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSSV', models.CharField(max_length=150)),
                ('GPA', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSSV', models.CharField(max_length=150)),
                ('Major', models.CharField(max_length=150)),
                ('JobStatus', models.CharField(max_length=150)),
                ('JobName', models.CharField(max_length=300)),
                ('JobAddress', models.CharField(max_length=300)),
                ('TimeToStart', models.DateField()),
                ('Feature', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSSV', models.CharField(max_length=150)),
                ('Salary', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSSV', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=150)),
                ('DateOfBirth', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=150)),
                ('AmountOfDonation', models.IntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.account')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSSV', models.CharField(max_length=150)),
                ('StartTimeShool', models.DateField()),
                ('FinishTimeSchool', models.DateField()),
                ('Grade', models.CharField(max_length=150)),
                ('Class', models.CharField(max_length=150)),
                ('Achievement', models.CharField(max_length=500)),
                ('Student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
