# Generated by Django 3.2.9 on 2021-12-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSSV', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
                ('FirstName', models.CharField(max_length=150)),
                ('LastName', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('PhoneNumber', models.CharField(max_length=150)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(max_length=1)),
                ('Hometown', models.CharField(max_length=150)),
                ('StartTimeShool', models.DateField()),
                ('FinishTimeSchool', models.DateField()),
                ('Achievement', models.CharField(max_length=500)),
                ('AmountOfDonation', models.IntegerField()),
                ('JobStatus', models.CharField(max_length=150)),
            ],
        ),
    ]
