# Generated by Django 3.2.8 on 2021-12-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
