# Generated by Django 3.2.8 on 2021-12-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_student_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='AmountOfDonation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
