# Generated by Django 3.2.8 on 2021-12-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_student_amountofdonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Achievement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
