# Generated by Django 3.2.8 on 2021-12-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_school_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='TimeToStart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
