# Generated by Django 3.2.8 on 2021-12-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_job_timetostart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Achievement',
            field=models.CharField(default='', max_length=500),
        ),
    ]
