# Generated by Django 3.2.8 on 2021-12-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_school_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Achievement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
