# Generated by Django 3.2.8 on 2021-12-05 23:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_alter_job_timetostart'),
        ('connection', '0002_auto_20211205_2314'),
        ('forum', '0002_auto_20211205_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='Admin', max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cmt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.comment')),
                ('g_cmt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connection.group_comment')),
                ('g_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connection.group_post')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.account')),
            ],
        ),
    ]
