# Generated by Django 3.2.9 on 2021-12-04 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=150)),
                ('group_infor', models.CharField(max_length=1000)),
                ('group_area', models.CharField(max_length=20)),
                ('group_class', models.CharField(max_length=20)),
                ('group_member', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group_post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g_post_title', models.CharField(max_length=150)),
                ('g_post_content', models.CharField(max_length=2000)),
                ('g_post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('g_post_comment', models.IntegerField(default=0)),
                ('g_post_image', models.ImageField(default='', upload_to='group_images')),
                ('g_post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.group')),
            ],
        ),
        migrations.CreateModel(
            name='Group_comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g_cmt_content', models.CharField(max_length=300)),
                ('g_cmt_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('g_cmt_image', models.ImageField(default='', upload_to='group_images')),
                ('g_cmt_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
                ('g_postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.group_post')),
            ],
        ),
    ]
