# Generated by Django 3.2.8 on 2021-12-05 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_job_timetostart'),
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_class',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_member',
        ),
        migrations.AlterField(
            model_name='group_comment',
            name='g_cmt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account'),
        ),
        migrations.AlterField(
            model_name='group_post',
            name='g_post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account'),
        ),
    ]
