# Generated by Django 3.2.8 on 2021-12-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateroom',
            name='lastMessage',
            field=models.TextField(default='', max_length=100),
        ),
    ]
