# Generated by Django 3.2.9 on 2021-12-02 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Messages', models.CharField(max_length=1000)),
                ('ReportDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
