# Generated by Django 3.2.9 on 2021-12-02 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=150)),
                ('post_content', models.CharField(max_length=2000)),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post_like', models.IntegerField(default=0)),
                ('post_comment', models.IntegerField(default=0)),
                ('post_image', models.ImageField(default='', upload_to='post_images')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cmt_content', models.CharField(max_length=300)),
                ('cmt_like', models.IntegerField(default=0)),
                ('cmt_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cmt_image', models.ImageField(default='', upload_to='post_images')),
                ('cmt_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.post')),
            ],
        ),
    ]
