# Generated by Django 3.2.8 on 2021-12-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_students'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account'),
        ),
    ]
