# Generated by Django 3.2.9 on 2021-12-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regis_teach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=150, null=True)),
                ('LastName', models.CharField(max_length=150, null=True)),
                ('teach_title', models.CharField(max_length=150)),
                ('teach_date', models.DateField()),
                ('teach_mess', models.CharField(max_length=500, null=True)),
                ('StudentCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=150, null=True)),
                ('LastName', models.CharField(max_length=150, null=True)),
                ('intro_title', models.CharField(max_length=150)),
                ('intro_content', models.CharField(default='', max_length=2000)),
                ('StudentCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=150)),
                ('LastName', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150, null=True)),
                ('PhoneNumber', models.CharField(max_length=150, null=True)),
                ('BankAccountNumber', models.CharField(max_length=20)),
                ('AmountOfDonation', models.IntegerField()),
                ('DonationDate', models.DateField()),
                ('Messages', models.CharField(max_length=500, null=True)),
                ('StudentCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
